version: "3"
services:


  api:
    container_name: api_service
    build:
      context: ./services/_api
      dockerfile: api.fa.dockerfile
      network: host
      args:
        - ENVIRONMENT=${ENVIRONMENT-dev}
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    ports:
      - 8000:8000
    volumes:
      - ./services/_api/src:/app
      - ~/.config/gcloud/application_default_credentials.json:/tmp/keys/application_default_credentials.json
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port ${PORT-8000} --log-level info
    # command: sh -c "while true; do sleep 1; done"


  _web:
    container_name: web_service
    build:
      context: ./services/_web
      dockerfile: web.ngfb.dockerfile
      network: host
    ports:
      - 8100:8100
    volumes:
      - ./services/_web/app:/home/node/app
    # command: "ionic serve --external"
    # command: sh -c "while true; do sleep 1; done"

