version: "3"
services:

  _api:
    depends_on:
      - db-local
      - cloudsql-proxy

  _web:
    depends_on:
      - _api

  db-local:
    container_name: db-local
    image: postgres:14-alpine
    build:
      context: ./services/_db
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=_db
    volumes:
      - db-local-data:/var/lib/postgresql/data/pgdata
      # - ./services/_db/sql:/docker-entrypoint-initdb.d/
    command: postgres -c log_statement=all


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db-local
    ports:
      - ${PGADMIN_PORT:-5050}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-postgres}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-postgres}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      # - PGADMIN_LISTEN_ADDRESS=
      # - PGADMIN_LISTEN_PORT=5432
      # - PGADMIN_SERVER_JSON_FILE
    volumes:
       - pgadmin-data:/var/lib/pgadmin


  cloudsql-proxy: # access your cloud sql database from your local machine
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    ports:
      - 5433:5432
    volumes:
      - ./services/database/keys:/config
    restart: always
    command: /cloud_sql_proxy --dir=/cloudsql -instances=your-gcp:europe-west1:quick-desk-sql-instance=tcp:0.0.0.0:5432 -credential_file=/config/google-creds.json

  redis:
    container_name: redis
    image: redis:alpine
    # environment:
      # - REDIS_PASSWORD=ubuntu
      # - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server
    # restart: unless-stopped


  
  redisinsight: # redis db visualization dashboard
    container_name: redisinsight
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight-data:/db


volumes:
  db-local-data:
  pgadmin-data:
  redis-data:
  redisinsight-data:
